spring:
  application:
    name: crypto-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

coingecko:
  api-key: ${COINGECKO_API_KEY:COINGECKO_KEY_NOT_FOUND}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
